## **Goal**

The goal of this project is to practice **data cleaning and feature engineering using Pandas** by working with a real-world Data Science jobs dataset. The project focuses on identifying and handling missing/invalid values, removing duplicates, transforming inconsistent data formats, and creating meaningful features from existing columns.

In [227]:
# importing libraries

import numpy as np
import pandas as pd
import datetime as dt

In [2]:
# loading the dataset

df = pd.read_csv('Uncleaned_DS_jobs.csv')

## **Summary of the dataset**
This is a scrapped data of Data Science job posts from Glassdoor.


#### Columns -

* Job Title - title of the job
* Salary Estimate - estimated salary
* Job Description - entire job description
* Rating - rating of the job post
* Company Name - name of the company that posted the job
* Location - location of the company
* Headquarters - location of headquarters
* Size - number of employees in the company
* Founded - year the company was founded
* Type of ownership - Public/Private/Non-profit
* Industry, Sector - field of the job
* Revenue - total revenue of the company
* Competitors - competitors of the company

### **Data Profiling**

In [11]:
# 672 rows, 15 columns

df.shape

(672, 15)

In [3]:
# let's see how our data looks

df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [4]:
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
667,667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
668,668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
669,669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1
670,670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1
671,671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1

In [5]:
df.sample(10)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
457,457,Data Scientist,$69K-$116K (Glassdoor est.),Work in a fast growing startup with unlimited ...,-1.0,Stride Search,"San Francisco, CA","Westlake Village, CA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1
219,219,"Senior Machine Learning Scientist - Bay Area, CA",$79K-$106K (Glassdoor est.),Passionate about precision medicine and advanc...,3.3,Tempus Labs\n3.3,"Redwood City, CA","Chicago, IL",501 to 1000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
228,228,Machine Learning Engineer,$71K-$123K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1
262,262,Data Scientist-Human Resources,$91K-$150K (Glassdoor est.),"Lexington, MA, US\n\n#job-location.job-locatio...",3.8,MIT Lincoln Laboratory\n3.8,"Lexington, MA","Lexington, MA",1001 to 5000 employees,1951,Nonprofit Organization,Aerospace & Defense,Aerospace & Defense,Unknown / Non-Applicable,-1
221,221,Data Scientist/Machine Learning,$71K-$123K (Glassdoor est.),"PulsePoint™, a global programmatic advertising...",4.3,PulsePoint\n4.3,"New York, NY","New York, NY",51 to 200 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Crossix Solutions Inc., AppNexus, The Trade Desk"
264,264,"Data Scientist - Statistics, Mid-Career",$91K-$150K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310919\n\n...,3.7,Pacific Northwest National Laboratory\n3.7,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
137,137,Data Scientist,$90K-$109K (Glassdoor est.),Upstart is a leading AI lending platform partn...,4.2,Upstart\n4.2,"San Mateo, CA","San Mateo, CA",201 to 500 employees,2012,Company - Private,Lending,Finance,Unknown / Non-Applicable,-1
352,352,Decision Scientist,$122K-$146K (Glassdoor est.),Are you passionate about Decision Science?\n\n...,4.5,Johns Hopkins University Applied Physics Labor...,"Laurel, MD","Laurel, MD",5001 to 10000 employees,1942,Nonprofit Organization,Aerospace & Defense,Aerospace & Defense,$1 to $2 billion (USD),"MIT Lincoln Laboratory, Lockheed Martin, North..."
435,435,Data Scientist,$79K-$133K (Glassdoor est.),Job Description\nWe are looking for the sharpe...,5.0,PeopleCom\n5.0,"McLean, VA","Reston, VA",1 to 50 employees,-1,Company - Private,-1,-1,$1 to $5 million (USD),-1
629,629,Data Scientist,$87K-$141K (Glassdoor est.),Job Description\nData Scientist\nDuration: 6+ ...,4.7,CRS Group\n4.7,"Chicago, IL","Itasca, IL",51 to 200 employees,1994,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1

In [6]:
# Observations -

# index column is just giving index - drop/set the column as index column
# Salary Estimate column has unnessary (Glassdoor est.) chars at the end - filter it out
# Company Name - a few rows have '\nX' at the end - filter it out
# Size - filter out 'employees'
# Revenue - filter out '(USD)'
# Location - seems to be of US
# some placeholders like -1/Unknown instead of NULL

In [7]:
# NOTE -

# This data is scraped from Glassdoor, so data will have placeholders like -1/Unknown/Not-Applicable
# these place holders should be treated as NULL

In [12]:
# 172 different job titles

df['Job Title'].nunique()

172

In [14]:
# max rating is 5.0 so logically rating should be between 0.0 - 5.0
# unless the value's a placeholder like -1

df['Rating'].max()

5.0

In [16]:
# 432 companies made one/multiple job posts

df['Company Name'].nunique()

432

In [18]:
# 13 types of ownership - so this is a categorical column

df['Type of ownership'].nunique()

13

In [19]:
# 2 of the 13 are placeholders, so 11 types of ownership

df['Type of ownership'].unique()

array(['Nonprofit Organization', 'Company - Public',
       'Private Practice / Firm', 'Company - Private', 'Government',
       'Subsidiary or Business Segment', 'Other Organization', '-1',
       'Unknown', 'Hospital', 'Self-employed', 'College / University',
       'Contract'], dtype=object)

In [20]:
# 58 different industries

df['Industry'].nunique()

58

In [21]:
# 23 different sectors

df['Sector'].nunique()

23

In [22]:
# info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    object
 6   Location           672 non-null    object
 7   Headquarters       672 non-null    object
 8   Size               672 non-null    object
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    object
 11  Industry           672 non-null    object
 12  Sector             672 non-null    object
 13  Revenue            672 non-null    object
 14  Competitors        672 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 78.9+ KB

In [23]:
# data types need to be fixed
# it shows no NULL values - because of the presence of placeholders

### **Data Cleaning**

#### *Column wise inspection*

In [24]:
df.columns

Index(['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

*Index*

In [25]:
df['index']

0        0
1        1
2        2
3        3
4        4
      ...
667    667
668    668
669    669
670    670
671    671
Name: index, Length: 672, dtype: int64

In [26]:
# just an index column, needs to be replaced/removed

df.drop(columns=['index'], inplace=True)

In [27]:
# let's check if changes are made

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

*Salary Estimate*

In [28]:
df['Salary Estimate']

0      $137K-$171K (Glassdoor est.)
1      $137K-$171K (Glassdoor est.)
2      $137K-$171K (Glassdoor est.)
3      $137K-$171K (Glassdoor est.)
4      $137K-$171K (Glassdoor est.)
                   ...
667    $105K-$167K (Glassdoor est.)
668    $105K-$167K (Glassdoor est.)
669    $105K-$167K (Glassdoor est.)
670    $105K-$167K (Glassdoor est.)
671    $105K-$167K (Glassdoor est.)
Name: Salary Estimate, Length: 672, dtype: object

In [30]:
df['Salary Estimate'] = df['Salary Estimate'].str.replace('(Glassdoor est.)', '').str.strip()

In [31]:
# checking if changes are made in df

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [33]:
# now let's check for placeholders that should be NULL

df[(df['Salary Estimate'] == '') | (df['Salary Estimate'] == '-1') | (df['Salary Estimate'] == 'Unknown / Non-Applicable')].shape[0]

0

*Job Title*

In [34]:
# checking for placeholders that should be NULL

df[(df['Job Title'] == '') | (df['Job Title'] == '-1') | (df['Job Title'] == 'Unknown / Non-Applicable')].shape[0]

0

*Job Description*

In [35]:
# checking for placeholders that should be NULL

df[(df['Job Description'] == '') | (df['Job Description'] == '-1') | (df['Job Description'] == 'Unknown / Non-Applicable')].shape[0]

0

*Rating*

In [37]:
df['Rating']

0      3.1
1      4.2
2      3.8
3      3.5
4      2.9
      ...
667    3.6
668   -1.0
669   -1.0
670    5.0
671    2.7
Name: Rating, Length: 672, dtype: float64

In [38]:
df['Rating'].max()

5.0

In [39]:
# that's a placeholder

df['Rating'].min()

-1.0

In [41]:
df[df['Rating'] < 0.0].shape[0]

50

In [50]:
# replacing the placeholders with NULL

df.loc[df['Rating'] < 0.0, 'Rating'] = np.nan

In [51]:
# checking if changes are made

df[df['Rating'] < 0.0].shape[0]

0

In [52]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

*Company Name*

In [53]:
df['Company Name']

0               Healthfirst\n3.1
1                   ManTech\n4.2
2            Analysis Group\n3.8
3                   INFICON\n3.5
4        Affinity Solutions\n2.9
                 ...
667                TRANZACT\n3.6
668                         JKGT
669                   AccessHope
670    ChaTeck Incorporated\n5.0
671           1-800-Flowers\n2.7
Name: Company Name, Length: 672, dtype: object

In [56]:
# filtering out '\nX' from rows than have them

df['Company Name'] = df['Company Name'].str.split('\n').str[0]

In [57]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [58]:
# checking for placeholders

df[(df['Company Name'] == '') | (df['Company Name'] == '-1') | (df['Company Name'] == 'Unknown / Non-Applicable')].shape[0]

0

*Location*

In [59]:
# checking for placeholders

df[(df['Location'] == '') | (df['Location'] == '-1') | (df['Location'] == 'Unknown / Non-Applicable')].shape[0]

0

*Headquarters*

In [60]:
# checking for placeholders

df[(df['Headquarters'] == '') | (df['Headquarters'] == '-1') | (df['Headquarters'] == 'Unknown / Non-Applicable')].shape[0]

31

In [62]:
# 31 rows with placeholders

# fixing it

df[(df['Headquarters'] == '') | (df['Headquarters'] == '-1') | (df['Headquarters'] == 'Unknown / Non-Applicable')]['Headquarters']

154    -1
158    -1
258    -1
351    -1
357    -1
358    -1
359    -1
360    -1
361    -1
362    -1
388    -1
389    -1
424    -1
459    -1
495    -1
496    -1
497    -1
498    -1
499    -1
500    -1
504    -1
519    -1
555    -1
613    -1
637    -1
650    -1
656    -1
657    -1
660    -1
668    -1
669    -1
Name: Headquarters, dtype: object

In [63]:
# placeholder is '-1'

df.loc[df['Headquarters'] == '-1', 'Headquarters'] = np.nan

In [64]:
df[(df['Headquarters'] == '') | (df['Headquarters'] == '-1') | (df['Headquarters'] == 'Unknown / Non-Applicable')].shape[0]

0

*Size*

In [65]:
df['Size']

0       1001 to 5000 employees
1      5001 to 10000 employees
2       1001 to 5000 employees
3        501 to 1000 employees
4          51 to 200 employees
                ...
667     1001 to 5000 employees
668                         -1
669                         -1
670          1 to 50 employees
671     1001 to 5000 employees
Name: Size, Length: 672, dtype: object

In [70]:
# filtering out 'employees'

df['Size'] = df['Size'].str.replace('employees', '').str.strip()

In [71]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [72]:
# checking for placeholders

df[(df['Size'] == '-1') | (df['Size'] == 'Unknown / Non-Applicable')].shape[0]

27

In [75]:
# 27 rows with placeholders

# fixing it

df.loc[((df['Size'] == '-1')|(df['Size'] == 'Unknown / Non-Applicable')), 'Size'] = np.nan

In [76]:
df[(df['Size'] == '-1') | (df['Size'] == 'Unknown / Non-Applicable')].shape[0]

0

*Founded*

In [77]:
df['Founded']

0      1993
1      1968
2      1981
3      2000
4      1998
       ...
667    1989
668      -1
669      -1
670      -1
671    1976
Name: Founded, Length: 672, dtype: int64

In [79]:
# checking for placeholders

df[df['Founded'] == -1].shape[0]

118

In [80]:
# 118 rows with placeholders

# fixing it

df.loc[df['Founded'] == -1, 'Founded'] = np.nan

In [81]:
df[df['Founded'] == -1].shape[0]

0

In [82]:
# checking for invalid values

df['Founded'].min()

1781.0

In [83]:
df['Founded'].max()

2019.0

In [85]:
# no invalid values found

In [122]:
# fixing the data type

df['Founded'] = df['Founded'].astype('Int64')

*Type of ownership*

In [86]:
df['Type of ownership']

0       Nonprofit Organization
1             Company - Public
2      Private Practice / Firm
3             Company - Public
4            Company - Private
                ...
667          Company - Private
668                         -1
669                         -1
670          Company - Private
671           Company - Public
Name: Type of ownership, Length: 672, dtype: object

In [87]:
# checking for placeholders

df[(df['Type of ownership'] == '') | (df['Type of ownership'] == '-1') | (df['Type of ownership'] == 'Unknown / Non-Applicable')].shape[0]

27

In [88]:
# 27 rows with placeholders

# fixing it

df.loc[((df['Type of ownership'] == '')|(df['Type of ownership'] == '-1')|(df['Type of ownership'] == 'Unknown / Non-Applicable')), 'Type of ownership'] = np.nan

In [89]:
df[(df['Type of ownership'] == '') | (df['Type of ownership'] == '-1') | (df['Type of ownership'] == 'Unknown / Non-Applicable')].shape[0]

0

In [90]:
df['Type of ownership'].unique()

array(['Nonprofit Organization', 'Company - Public',
       'Private Practice / Firm', 'Company - Private', 'Government',
       'Subsidiary or Business Segment', 'Other Organization', nan,
       'Unknown', 'Hospital', 'Self-employed', 'College / University',
       'Contract'], dtype=object)

In [91]:
# we missed a placeholder - Unknown

df[df['Type of ownership'] == 'Unknown'].shape[0]

4

In [92]:
df.loc[df['Type of ownership'] == 'Unknown', 'Type of ownership'] = np.nan

In [93]:
df[df['Type of ownership'] == 'Unknown'].shape[0]

0

In [95]:
df['Type of ownership'].unique()

array(['Nonprofit Organization', 'Company - Public',
       'Private Practice / Firm', 'Company - Private', 'Government',
       'Subsidiary or Business Segment', 'Other Organization', nan,
       'Hospital', 'Self-employed', 'College / University', 'Contract'],
      dtype=object)

In [96]:
# now, let's change the column's data type

df['Type of ownership'] = df['Type of ownership'].astype('category')

*Industry*

In [97]:
df['Industry']

0                         Insurance Carriers
1                     Research & Development
2                                 Consulting
3      Electrical & Electronic Manufacturing
4                    Advertising & Marketing
                       ...
667                  Advertising & Marketing
668                                       -1
669                                       -1
670                  Advertising & Marketing
671                                Wholesale
Name: Industry, Length: 672, dtype: object

In [98]:
# checking for placeholders

df[(df['Industry'] == '') | (df['Industry'] == '-1') | (df['Industry'] == 'Unknown / Non-Applicable') | (df['Industry'] == 'Unknown')].shape[0]

71

In [99]:
# 71 rows with placeholders

# fixing it

df.loc[((df['Industry'] == '')|(df['Industry'] == '-1')|(df['Industry'] == 'Unknown / Non-Applicable')|(df['Industry'] == 'Unknown')), 'Industry'] = np.nan

In [100]:
df[(df['Industry'] == '') | (df['Industry'] == '-1') | (df['Industry'] == 'Unknown / Non-Applicable') | (df['Industry'] == 'Unknown')].shape[0]

0

In [101]:
# now, let's change the data type

df['Industry'] = df['Industry'].astype('category')

In [102]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993.0,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968.0,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981.0,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000.0,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998.0,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

*Sector*

In [103]:
df['Sector']

0              Insurance
1      Business Services
2      Business Services
3          Manufacturing
4      Business Services
             ...
667    Business Services
668                   -1
669                   -1
670    Business Services
671    Business Services
Name: Sector, Length: 672, dtype: object

In [104]:
# checking for placeholders

df[(df['Sector'] == '') | (df['Sector'] == '-1') | (df['Sector'] == 'Unknown / Non-Applicable') | (df['Sector'] == 'Unknown')].shape[0]

71

In [105]:
# 71 rows with placeholders

# fixing it

df.loc[((df['Sector'] == '')|(df['Sector'] == '-1')|(df['Sector'] == 'Unknown / Non-Applicable')|(df['Sector'] == 'Unknown')), 'Sector'] = np.nan

In [106]:
df[(df['Sector'] == '') | (df['Sector'] == '-1') | (df['Sector'] == 'Unknown / Non-Applicable') | (df['Sector'] == 'Unknown')].shape[0]

0

In [107]:
# now, changing the data type

df['Sector'] = df['Sector'].astype('category')

*Revenue*

In [108]:
df['Revenue']

0        Unknown / Non-Applicable
1          $1 to $2 billion (USD)
2      $100 to $500 million (USD)
3      $100 to $500 million (USD)
4        Unknown / Non-Applicable
                  ...
667      Unknown / Non-Applicable
668                            -1
669                            -1
670        $1 to $5 million (USD)
671        $1 to $2 billion (USD)
Name: Revenue, Length: 672, dtype: object

In [109]:
# filtering '(USD)' and replacing million with M

df['Revenue'] = df['Revenue'].str.replace('(USD)', '').str.strip()

In [110]:
df['Revenue']

0      Unknown / Non-Applicable
1              $1 to $2 billion
2          $100 to $500 million
3          $100 to $500 million
4      Unknown / Non-Applicable
                 ...
667    Unknown / Non-Applicable
668                          -1
669                          -1
670            $1 to $5 million
671            $1 to $2 billion
Name: Revenue, Length: 672, dtype: object

In [111]:
# now, let's replace million with M and billion with B

df['Revenue'] = df['Revenue'].str.replace('million', 'M').str.strip()
df['Revenue'] = df['Revenue'].str.replace('billion', 'B').str.strip()

In [112]:
df['Revenue']

0      Unknown / Non-Applicable
1                    $1 to $2 B
2                $100 to $500 M
3                $100 to $500 M
4      Unknown / Non-Applicable
                 ...
667    Unknown / Non-Applicable
668                          -1
669                          -1
670                  $1 to $5 M
671                  $1 to $2 B
Name: Revenue, Length: 672, dtype: object

In [113]:
# checking for placeholders

df[(df['Revenue'] == '') | (df['Revenue'] == '-1') | (df['Revenue'] == 'Unknown') | (df['Revenue'] == 'Unknown / Non-Applicable')].shape[0]

240

In [114]:
# 240 rows with placeholders

# fixing it

df.loc[((df['Revenue'] == '') | (df['Revenue'] == '-1') | (df['Revenue'] == 'Unknown') | (df['Revenue'] == 'Unknown / Non-Applicable')), 'Revenue'] = np.nan

In [115]:
df[(df['Revenue'] == '') | (df['Revenue'] == '-1') | (df['Revenue'] == 'Unknown') | (df['Revenue'] == 'Unknown / Non-Applicable')].shape[0]

0

*Competitors*

In [117]:
df['Competitors']

0                EmblemHealth, UnitedHealth Group, Aetna
1                                                     -1
2                                                     -1
3      MKS Instruments, Pfeiffer Vacuum, Agilent Tech...
4                   Commerce Signals, Cardlytics, Yodlee
                             ...
667                                                   -1
668                                                   -1
669                                                   -1
670                                                   -1
671                                                   -1
Name: Competitors, Length: 672, dtype: object

In [116]:
# checking for placeholders

df[(df['Competitors'] == '') | (df['Competitors'] == '-1') | (df['Competitors'] == 'Unknown') | (df['Competitors'] == 'Unknown / Non-Applicable')].shape[0]

501

In [118]:
# 501 rows with placeholders

# fixing it

df.loc[((df['Competitors'] == '') | (df['Competitors'] == '-1') | (df['Competitors'] == 'Unknown') | (df['Competitors'] == 'Unknown / Non-Applicable')), 'Competitors'] = np.nan

In [119]:
df[(df['Competitors'] == '') | (df['Competitors'] == '-1') | (df['Competitors'] == 'Unknown') | (df['Competitors'] == 'Unknown / Non-Applicable')].shape[0]

0

In [120]:
# fixed placeholders and fixed the data types until here

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          672 non-null    object
 1   Salary Estimate    672 non-null    object
 2   Job Description    672 non-null    object
 3   Rating             622 non-null    float64
 4   Company Name       672 non-null    object
 5   Location           672 non-null    object
 6   Headquarters       641 non-null    object
 7   Size               645 non-null    object
 8   Founded            554 non-null    Int64
 9   Type of ownership  641 non-null    category
 10  Industry           601 non-null    category
 11  Sector             601 non-null    category
 12  Revenue            432 non-null    object
 13  Competitors        171 non-null    object
dtypes: Int64(1), category(3), float64(1), object(9)
memory usage: 64.1+ KB

At this point, we haven't completely cleaned the data.

To complete the data cleaning process, we first need to:

* Check for duplicate rows.
* Convert columns such as `Salary Estimate`, `Size`, and `Revenue` into useful numerical features, since their current values are stored as ranges and therefore have an `object` data type.
* Perform feature engineering to extract features such as `min_salary`, `max_salary`, `avg_salary`, etc.
* After these transformations, review and handle the remaining missing (`NaN`) values appropriately.

####*Duplicates*

In [127]:
df.duplicated().sum()

np.int64(13)

In [129]:
# there are 13 duplicate rows, inspecting them

df[df.duplicated(keep=False)].sort_values('Company Name')

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
361,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
498,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
497,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
496,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
495,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
362,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
499,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
500,Data Scientist,$95K-$119K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
359,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
358,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
357,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
360,Data Scientist,$122K-$146K,Job Overview: The Data Scientist is a key memb...,NaN,Hatch Data Inc,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
388,Data Scientist,$110K-$163K,"Job Description\nAs a Data Scientist, you will...",NaN,HireAi,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
389,Data Scientist,$110K-$163K,"Job Description\nAs a Data Scientist, you will...",NaN,HireAi,"San Francisco, CA",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
136,Senior Data Engineer,$90K-$109K,Lendio is looking to fill a position for a Sen...,4.9,Lendio,"Lehi, UT","Lehi, UT",201 to 500,2011,Company - Private,Lending,Finance,$50 to $100 M,NaN
131,Senior Data Engineer,$90K-$109K,Lendio is looking to fill a position for a Sen...,4.9,Lendio,"Lehi, UT","Lehi, UT",201 to 500,2011,Company - Private,Lending,Finance,$50 to $100 M,NaN
135,Machine Learning Engineer,$90K-$109K,Role Description\nTriplebyte screens and evalu...,3.2,Triplebyte,Remote,"San Francisco, CA",51 to 200,2015,Company - Private,Computer Hardware & Software,Information Technology,NaN,NaN
134,Machine Learning Engineer,$90K-$109K,Role Description\nTriplebyte screens and evalu...,3.2,Triplebyte,Remote,"San Francisco, CA",51 to 200,2015,Company - Private,Computer Hardware & Software,Information Technology,NaN,NaN

In [130]:
# these are geniune duplicates, dropping these

df.drop_duplicates(inplace=True)

In [132]:
# our dataset now has 659 rows

df.shape

(659, 14)

###**Feature Engineering**

*Salary Estimate*

In [133]:
df['Salary Estimate']

0      $137K-$171K
1      $137K-$171K
2      $137K-$171K
3      $137K-$171K
4      $137K-$171K
          ...
667    $105K-$167K
668    $105K-$167K
669    $105K-$167K
670    $105K-$167K
671    $105K-$167K
Name: Salary Estimate, Length: 659, dtype: object

In [147]:
# let's make min_salary, max_salary, avg_salary columns

df['min_salary($)'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[0].replace('K', '').replace('$', '').strip())*1000)

In [154]:
df['Salary Estimate'].apply(lambda x: int(x.split('-')[1].replace('K', '').replace('$', '').strip()))

ValueError: invalid literal for int() with base 10: '225(Employer est.)'

In [159]:
# so there is a row with max salary as 225('Employer est.)
# let's check how many rows are like this

df['Salary Estimate'].str.contains('(Employer est.)').sum()

/tmp/ipykernel_2364/4249352314.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['Salary Estimate'].str.contains('(Employer est.)').sum()

np.int64(20)

In [161]:
# 20 rows, let's fix them

df['Salary Estimate'] = df['Salary Estimate'].str.replace('(Employer est.)', '', regex=False).str.strip()

In [162]:
df['Salary Estimate'].str.contains('(Employer est.)').sum()

/tmp/ipykernel_2364/2427322217.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['Salary Estimate'].str.contains('(Employer est.)').sum()

np.int64(0)

In [165]:
# now, let's continue to make our max_salary column

df['max_salary($)'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[1].replace('K', '').replace('$', '').strip())*1000)

In [170]:
# avg_salary

df['avg_salary($)'] = df[['min_salary($)', 'max_salary($)']].mean(axis=1)

In [171]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary($),max_salary($),avg_salary($)
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000,154000.0
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 B,NaN,137000,171000,154000.0
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 M,NaN,137000,171000,154000.0
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 M,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000,154000.0
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",137000,171000,154000.0

*Size*

In [172]:
df['Size']

0       1001 to 5000
1      5001 to 10000
2       1001 to 5000
3        501 to 1000
4          51 to 200
           ...
667     1001 to 5000
668              NaN
669              NaN
670          1 to 50
671     1001 to 5000
Name: Size, Length: 659, dtype: object

In [178]:
df['Size'].apply(lambda x: x.split('to'))

AttributeError: 'float' object has no attribute 'split'

In [181]:
# we can't use apply function due to the presence of NaN values, so we'll use .str method

df['Size'].str.split('to').str[0].astype('Int32')

ValueError: invalid literal for int() with base 10: '10000+'

In [182]:
# now we found out that some values or not in range but like '10000+'

df['min_employees'] = (
    df['Size']
    .str.extract(r'(\d+)')[0]
    .astype('Int64')
)

In [183]:
df['max_employees'] = (
    df['Size']
    .str.extract(r'to\s*(\d+)')[0]
    .astype('Int64')
)

In [184]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary($),max_salary($),avg_salary($),min_employees,max_employees
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000,154000.0,1001,5000
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,Research & Development,Business Services,$1 to $2 B,NaN,137000,171000,154000.0,5001,10000
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 M,NaN,137000,171000,154000.0,1001,5000
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 M,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000,154000.0,501,1000
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",137000,171000,154000.0,51,200

*Revenue*

In [186]:
df['Revenue'].sample(10)

509           $10+ B
616       $2 to $5 B
587       $1 to $2 B
295              NaN
254    $50 to $100 M
170      $5 to $10 B
540    $50 to $100 M
327     $25 to $50 M
109      $5 to $10 M
201     $10 to $25 M
Name: Revenue, dtype: object

In [190]:
# there's some values as x+ B, some as x to y M/B
# we're creating 2 new columns - min_revenue, max_revenue
# but the catch is the values units will be in 'million'
# we'll follow the 1B = 1000M
# while also keeping in mind that values differ in type

df['Revenue'].sample(10)

599               NaN
403    $500 M to $1 B
579               NaN
641               NaN
502      $10 to $25 M
398    $100 to $500 M
180    $100 to $500 M
164            $10+ B
304      $25 to $50 M
280    $100 to $500 M
Name: Revenue, dtype: object

In [194]:
# creating a function to get min_revenue

def min_revenue(x):

  # for NaN values
  if pd.isna(x):
    return np.nan

  # for $x+ M/B values
  if '+' in x:
    if 'M' in x:
      value = float(x.split('+')[0].replace('$', '').strip())
    else:
      value = float(x.split('+')[0].replace('$', '').strip())*1000
    return value

  # for $x M/B to $y M/B values
  if 'to' in x:
    value = x.split('to')[0].replace('$', '').strip()
    if 'M' in value:
      value = float(value.replace('M', '').strip())
    elif 'B' in value:
      value = float(value.replace('B', '').strip())*1000
    value = float(value)
    return value

df['min_revenue($M)'] = df['Revenue'].apply(min_revenue)

In [250]:
# creating a function to get max_revenue

def max_revenue(x):

  # for NaN values
  if pd.isna(x):
    return np.nan

  # for $x+ M/B
  if '+' in x:
    return np.nan

  # for $x M/B to $y M/B values
  if 'to' in x:
    value = x.split('to')[1].replace('$', '').strip()
    if 'M' in value:
      value = float(value.replace('M', '').strip())
    elif 'B' in value:
      value = float(value.replace('B', '').strip())*1000
    value = float(value)
    return value

df['max_revenue($M)'] = df['Revenue'].apply(max_revenue)

In [196]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,Sector,Revenue,Competitors,min_salary($),max_salary($),avg_salary($),min_employees,max_employees,min_revenue($M),max_revenue($M)
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,...,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000,154000.0,1001,5000,NaN,NaN
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,...,Business Services,$1 to $2 B,NaN,137000,171000,154000.0,5001,10000,1.0,2000.0
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,...,Business Services,$100 to $500 M,NaN,137000,171000,154000.0,1001,5000,100.0,500.0
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,...,Manufacturing,$100 to $500 M,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000,154000.0,501,1000,100.0,500.0
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,...,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",137000,171000,154000.0,51,200,NaN,NaN

In [197]:
# let's create a new column, Job_State from the column Location

*Job State*

In [198]:
df['Location']

0           New York, NY
1          Chantilly, VA
2             Boston, MA
3             Newton, MA
4           New York, NY
             ...
667         Fort Lee, NJ
668    San Francisco, CA
669        Irwindale, CA
670    San Francisco, CA
671         New York, NY
Name: Location, Length: 659, dtype: object

In [204]:
df['Location'].apply(lambda x: x.split(',')[1])

IndexError: list index out of range

In [209]:
# we're getting this error because state of some Locations might not be mentioned
# let's fix it

pd.isna(df['Location'].str.split(',').str[1]).sum()

np.int64(22)

In [211]:
# 22 Locations don't have states in our data

df['Job State'] = df['Location'].str.split(',').str[1].str.strip()

In [212]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,Revenue,Competitors,min_salary($),max_salary($),avg_salary($),min_employees,max_employees,min_revenue($M),max_revenue($M),Job State
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,...,NaN,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000,154000.0,1001,5000,NaN,NaN,NY
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,...,$1 to $2 B,NaN,137000,171000,154000.0,5001,10000,1.0,2000.0,VA
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,...,$100 to $500 M,NaN,137000,171000,154000.0,1001,5000,100.0,500.0,MA
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,...,$100 to $500 M,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000,154000.0,501,1000,100.0,500.0,MA
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,...,NaN,"Commerce Signals, Cardlytics, Yodlee",137000,171000,154000.0,51,200,NaN,NaN,NY

In [213]:
# let's create a new column Same State which returns 1 if Job State is same state as Headquarters else 0

*Same State*

In [266]:
df['same_state'] = (
    df['Headquarters'].str.split(',').str[1].str.strip()
    == df['Job State']
).astype('Int64')

df.loc[
    df['Headquarters'].isna() | df['Job State'].isna(),
    'same_state'
] = pd.NA

In [223]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,Competitors,min_salary($),max_salary($),avg_salary($),min_employees,max_employees,min_revenue($M),max_revenue($M),Job State,same_state
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,...,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000,154000.0,1001,5000,NaN,NaN,NY,1
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,...,NaN,137000,171000,154000.0,5001,10000,1.0,2000.0,VA,1
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,...,NaN,137000,171000,154000.0,1001,5000,100.0,500.0,MA,1
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,...,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000,154000.0,501,1000,100.0,500.0,MA,0
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,...,"Commerce Signals, Cardlytics, Yodlee",137000,171000,154000.0,51,200,NaN,NaN,NY,1

In [224]:
# let's create a column company_age which represents the age of company since Founded

*Company Age*

In [233]:
df['company_age'] = dt.datetime.now().year - df['Founded']

In [234]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,min_salary($),max_salary($),avg_salary($),min_employees,max_employees,min_revenue($M),max_revenue($M),Job State,same_state,company_age
0,Sr Data Scientist,$137K-$171K,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000,1993,Nonprofit Organization,...,137000,171000,154000.0,1001,5000,NaN,NaN,NY,1,33
1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000,1968,Company - Public,...,137000,171000,154000.0,5001,10000,1.0,2000.0,VA,1,58
2,Data Scientist,$137K-$171K,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000,1981,Private Practice / Firm,...,137000,171000,154000.0,1001,5000,100.0,500.0,MA,1,45
3,Data Scientist,$137K-$171K,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000,2000,Company - Public,...,137000,171000,154000.0,501,1000,100.0,500.0,MA,0,26
4,Data Scientist,$137K-$171K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200,1998,Company - Private,...,137000,171000,154000.0,51,200,NaN,NaN,NY,1,28

In [235]:
# let's create a column called job_simp which represents the simplified job title

In [236]:
df['Job Title'].sample(10)

351                            Data Scientist
565                         Big Data Engineer
138                              Data Analyst
193                            Data Scientist
17                             Data Scientist
114                            Data Scientist
571    Data Scientist / Applied Mathematician
395    Data Solutions Engineer - Data Modeler
650    Scientist / Group Lead, Cancer Biology
125    Sr. ML/Data Scientist - AI/NLP/Chatbot
Name: Job Title, dtype: object

In [254]:
df['job_simp'] = df['Job Title'].str.split(r"/|-|\|(|)|,").str[0].str.strip()

In [255]:
df[['Job Title', 'job_simp']].sample(20)

                                             Job Title               job_simp
299                                     Data Scientist         Data Scientist
440                                     Data Scientist         Data Scientist
103                              Senior Data Scientist  Senior Data Scientist
40                                        Data Analyst           Data Analyst
637                                     Data Scientist         Data Scientist
595                                     Data Scientist         Data Scientist
113                                      Data Engineer          Data Engineer
13                                        Data Modeler           Data Modeler
11                                      Data Scientist         Data Scientist
209         Data Scientist - TS/SCI FSP or CI Required         Data Scientist
275                                     Data Scientist         Data Scientist
547                                     Data Scientist         Data Scientist
536                                     Data Scientist         Data Scientist
42                                      Data Analyst I         Data Analyst I
569                      Aviation AI/ML Data Scientist            Aviation AI
421        Analytics - Business Assurance Data Analyst              Analytics
542  COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPU...     COMPUTER SCIENTIST
269            Data Engineer, Digital & Comp Pathology          Data Engineer
551                              Senior Data Scientist  Senior Data Scientist
490                                     Data Scientist         Data Scientist

In [243]:
# let's create a column seniority which returns 1 if the job post is for senior position

*Seniority*

In [252]:
df['job_simp'].str.contains(r'\bSr\b|\bSenior\b', case=False, na=False).sum()

np.int64(75)

In [247]:
# 75 jobs that are posted are for senior position

df['seniority'] = df['job_simp'].str.contains(r'\bSr\b|\bSenior\b', case=False, na=False).apply(lambda x: 1 if x else 0)

*Final Validation*

In [248]:
df.shape

(659, 26)

In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 659 entries, 0 to 671
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          659 non-null    object
 1   Salary Estimate    659 non-null    object
 2   Job Description    659 non-null    object
 3   Rating             620 non-null    float64
 4   Company Name       659 non-null    object
 5   Location           659 non-null    object
 6   Headquarters       639 non-null    object
 7   Size               643 non-null    object
 8   Founded            552 non-null    Int64
 9   Type of ownership  639 non-null    category
 10  Industry           599 non-null    category
 11  Sector             599 non-null    category
 12  Revenue            431 non-null    object
 13  Competitors        171 non-null    object
 14  min_salary($)      659 non-null    int64
 15  max_salary($)      659 non-null    int64
 16  avg_salary($)      659 non-null    float64
 17  min_employees      626 non-null    Int64
 18  max_employees      546 non-null    Int64
 19  min_revenue($M)    417 non-null    float64
 20  max_revenue($M)    354 non-null    float64
 21  Job State          637 non-null    object
 22  same_state         617 non-null    Int64
 23  company_age        552 non-null    Int64
 24  job_simp           659 non-null    object
 25  seniority          659 non-null    int64
dtypes: Int64(5), category(3), float64(4), int64(3), object(11)
memory usage: 132.3+ KB

In [256]:
df.isna().sum()

Job Title              0
Salary Estimate        0
Job Description        0
Rating                39
Company Name           0
Location               0
Headquarters          20
Size                  16
Founded              107
Type of ownership     20
Industry              60
Sector                60
Revenue              228
Competitors          488
min_salary($)          0
max_salary($)          0
avg_salary($)          0
min_employees         33
max_employees        113
min_revenue($M)      242
max_revenue($M)      305
Job State             22
same_state            42
company_age          107
job_simp               0
seniority              0
dtype: int64

In [257]:
df.duplicated().sum()

np.int64(0)

In [258]:
(df['min_salary($)'] > df['max_salary($)']).sum()

np.int64(0)

In [259]:
(df['min_employees'] > df['max_employees']).sum()

np.int64(0)

In [260]:
(
    (df['min_revenue($M)'] > df['max_revenue($M)'])
    & df['max_revenue($M)'].notna()
).sum()

np.int64(0)

In [261]:
df[['min_salary($)', 'max_salary($)', 'avg_salary($)']].describe()

       min_salary($)  max_salary($)  avg_salary($)
count     659.000000     659.000000     659.000000
mean    99066.767830  148464.339909  123765.553869
std     33266.334795   48387.743556   39907.282895
min     31000.000000   56000.000000   43500.000000
25%     79000.000000  119000.000000  103000.000000
50%     91000.000000  133000.000000  114000.000000
75%    122000.000000  165000.000000  136500.000000
max    212000.000000  331000.000000  271500.000000

In [262]:
df[
    ['Salary Estimate', 'min_salary($)', 'max_salary($)', 'avg_salary($)']
].sample(10)

    Salary Estimate  min_salary($)  max_salary($)  avg_salary($)
111      $99K-$132K          99000         132000       115500.0
321     $145K-$225K         145000         225000       185000.0
90       $79K-$131K          79000         131000       105000.0
298     $141K-$225K         141000         225000       183000.0
655     $105K-$167K         105000         167000       136000.0
522     $212K-$331K         212000         331000       271500.0
310     $145K-$225K         145000         225000       185000.0
36       $75K-$131K          75000         131000       103000.0
350     $122K-$146K         122000         146000       134000.0
222      $71K-$123K          71000         123000        97000.0

In [263]:
df[
    ['Size', 'min_employees', 'max_employees']
].sample(10)

              Size  min_employees  max_employees
64      201 to 500            201            500
166  5001 to 10000           5001          10000
528      51 to 200             51            200
240      51 to 200             51            200
435        1 to 50              1             50
68     501 to 1000            501           1000
517      51 to 200             51            200
495            NaN           <NA>           <NA>
462        1 to 50              1             50
217    501 to 1000            501           1000

In [264]:
df[
    ['Revenue', 'min_revenue($M)', 'max_revenue($M)']
].sample(10)

            Revenue  min_revenue($M)  max_revenue($M)
97           $10+ B          10000.0              NaN
300          $10+ B          10000.0              NaN
485             NaN              NaN              NaN
414      $1 to $5 M              1.0              5.0
289    $10 to $25 M             10.0             25.0
347          $10+ B          10000.0              NaN
30   $100 to $500 M            100.0            500.0
133  $100 to $500 M            100.0            500.0
493          $10+ B          10000.0              NaN
522             NaN              NaN              NaN

In [268]:
df.to_csv('cleaned_transformed_DS_jobs.csv', index=False)